Revert the part of revision 26642 that is in fortran/test and causes the error "undefined reference to `verify_fortran_integer_4_". files:     tH5P_F03.f90     tf.f90
Tested:  h5committest and several failed daily tests.